on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          rtools-version: '42'
          windows-path-include-rtools: true

      - name: get info on gcc version and path
        if: matrix.config.os == 'windows-latest'
        run: |
          g++ -v
          echo $env:GITHUB_PATH
